services:
  - type: web
    name: streetpaws
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false